// ページ内のすべてのテキストラベル（オブジェクト形式）

const labels = {
	// Header コンポーネント
	HEADER_TITLE: 'Tsubasa Nishizuka - Portfolio',
	HEADER_SUBTITLE: 'AI開発・クラウド・フルスタック・モバイル開発の総合技術ポートフォリオ',
	HEADER_DESCRIPTION: 'Next.js 15 + TypeScript + PostgreSQL',
	HEADER_STATUS_NEXTJS: 'Next.js 15',
	HEADER_STATUS_POSTGRESQL: 'PostgreSQL',
	HEADER_STATUS_CONTABO: 'Contabo Server',

	// QuickAccess コンポーネント
	QUICK_ACCESS_TITLE: '🚀 クイックアクセス',
	QUICK_ACCESS_HEADER: 'ログイン',
	QUICK_ACCESS_BUTTON: 'ログイン / Sign In',
	QUICK_ACCESS_DEMO_TITLE: '🧪 デモアカウント（すぐにお試しいただけます）',
	QUICK_ACCESS_USER_ROLE: '👤 ユーザー',
	QUICK_ACCESS_USER_EMAIL: 'user@demo.com',
	QUICK_ACCESS_USER_PASSWORD: 'password123',
	QUICK_ACCESS_ADMIN_ROLE: '👨‍💼 管理者',
	QUICK_ACCESS_ADMIN_EMAIL: 'admin@demo.com',
	QUICK_ACCESS_ADMIN_PASSWORD: 'password123',
	QUICK_ACCESS_MASTER_ROLE: '👑 マスター',
	QUICK_ACCESS_MASTER_EMAIL: 'master@demo.com',
	QUICK_ACCESS_MASTER_PASSWORD: 'password123',
	QUICK_ACCESS_PASSWORD_LABEL: 'パスワード:',
	QUICK_ACCESS_LOGIN_BUTTON: 'ログイン',

	// UserRegistration コンポーネント
	USER_REG_TITLE: '新規アカウント作成',
	USER_REG_USER_TITLE: 'ユーザー登録',
	USER_REG_USER_DESC: 'ユーザー機能がご利用いただけます。ユーザー用画面にアクセス可能。',
	USER_REG_USER_BUTTON: 'ユーザー登録',
	USER_REG_ADMIN_TITLE: '管理者登録',
	USER_REG_ADMIN_DESC: 'システム管理機能をご利用いただけます。ユーザー管理・設定変更が可能。',
	USER_REG_ADMIN_BUTTON: '管理者登録',
	USER_REG_MASTER_TITLE: 'マスター登録',
	USER_REG_MASTER_DESC: '最高権限でのアクセスが可能です。システム全体の完全制御権限。',
	USER_REG_MASTER_BUTTON: 'マスター登録',

	// AIFeatures コンポーネント（サービス別）
	AI_FEATURES_TITLE: 'AI開発サービス',

	AI_SALES_NAME: '営業AI',
	AI_SALES_DESC: '見込み客対応からスケジューリング、フォローアップまで営業活動を自動化・強化します。',
	AI_SALES_FEATURE1: 'アウトバウンド営業',
	AI_SALES_FEATURE2: 'スケジュール調整・リマインド',
	AI_SALES_FEATURE3: 'ワークフロー自動処理',

	AI_SUPPORT_NAME: 'サポートAI',
	AI_SUPPORT_DESC: '複数チャネルの問合せを一元化し、迅速で正確なカスタマーサポートを提供します。',
	AI_SUPPORT_FEATURE1: 'Web/電話/LINE/メール/SNS対応',
	AI_SUPPORT_FEATURE2: '面接日程調整・自動通知',
	AI_SUPPORT_FEATURE3: 'HubSpot等との統合',

	AI_OFFICE_NAME: '事務・バックオフィスAI',
	AI_OFFICE_DESC: '請求書や契約書の作成・管理、経理処理などのバックオフィス業務を効率化します。',
	AI_OFFICE_FEATURE1: 'ワークフロー自動処理',
	AI_OFFICE_FEATURE2: 'スケジュール調整・リマインド',
	AI_OFFICE_FEATURE3: '事務・バックオフィスAI',

	AI_MANAGEMENT_NAME: '経営支援AI',
	AI_MANAGEMENT_DESC: 'データに基づく意思決定を支援し、売上・市場・競合を多角的に分析します。',
	AI_MANAGEMENT_FEATURE1: 'AIアナリスト',
	AI_MANAGEMENT_FEATURE2: '売上・顧客データ分析',
	AI_MANAGEMENT_FEATURE3: '施策提案',

	AI_ACCOUNTING_NAME: '経理AI',
	AI_ACCOUNTING_DESC: '仕訳や決算など定型業務を自動化し、正確性とスピードを両立します。',
	AI_ACCOUNTING_FEATURE1: 'AI経理エージェント',
	AI_ACCOUNTING_FEATURE2: '請求書処理自動化',
	AI_ACCOUNTING_FEATURE3: '財務分析・レポート',

	AI_HR_NAME: '人事AI',
	AI_HR_DESC: '採用から育成、評価まで人事プロセスを最適化します。',
	AI_HR_FEATURE1: '採用プロセス最適化',
	AI_HR_FEATURE2: '研修・育成プログラム',
	AI_HR_FEATURE3: 'パフォーマンス分析',

	// AIFeatures コンポーネント（統合・基盤機能）
	AI_INTEGRATION_TITLE: '統合・基盤機能',
	AI_INTEGRATION_FEATURE1_NAME: 'セキュリティ',
	AI_INTEGRATION_FEATURE1_DESC: 'エンタープライズレベルのセキュリティ',
	AI_INTEGRATION_FEATURE2_NAME: 'スコアリング',
	AI_INTEGRATION_FEATURE2_DESC: '商談確度・顧客価値の自動算出',
	AI_INTEGRATION_FEATURE3_NAME: 'API連携',
	AI_INTEGRATION_FEATURE3_DESC: '既存システムとのシームレス統合',
	AI_INTEGRATION_FEATURE4_NAME: '分析・レポート',
	AI_INTEGRATION_FEATURE4_DESC: '詳細なパフォーマンス分析レポート',

	// AIFeatures コンポーネント（改善効果）
	AI_IMPROVEMENT_TITLE: '可能な具体的な業務改善効果',

	AI_IMPROVEMENT_SALES_TITLE: '売上向上',
	AI_IMPROVEMENT_SALES_DESC: '見込み客対応の自動化や最適な提案で成約率を高めます。',
	AI_IMPROVEMENT_SALES_FEATURE1: '営業効率30-50%向上',
	AI_IMPROVEMENT_SALES_FEATURE2: '商談成約率20-40%改善',
	AI_IMPROVEMENT_SALES_FEATURE3: '15-25%アップ',

	AI_IMPROVEMENT_EFFICIENCY_TITLE: 'コスト削減',
	AI_IMPROVEMENT_EFFICIENCY_DESC: '定型作業の自動化により工数を削減し、価値業務へ集中できます。',
	AI_IMPROVEMENT_EFFICIENCY_FEATURE1: '人件費40-60%削減',
	AI_IMPROVEMENT_EFFICIENCY_FEATURE2: '事務処理時間70-80%短縮',
	AI_IMPROVEMENT_EFFICIENCY_FEATURE3: 'サポート対応コスト50%減',
	AI_IMPROVEMENT_EFFICIENCY_FEATURE4: '採用・研修コスト30%削減',
	AI_IMPROVEMENT_EFFICIENCY_FEATURE5: 'ヒューマンエラー90%以上削減',

	AI_IMPROVEMENT_ACCURACY_TITLE: '意思決定支援',
	AI_IMPROVEMENT_ACCURACY_DESC: 'データドリブンな分析により精度の高い意思決定を支援します。',
	AI_IMPROVEMENT_ACCURACY_FEATURE1: 'データ分析時間90%短縮',
	AI_IMPROVEMENT_ACCURACY_FEATURE2: '予測精度80-95%向上',
	AI_IMPROVEMENT_ACCURACY_FEATURE3: 'レポート作成自動化',
	AI_IMPROVEMENT_ACCURACY_FEATURE4: 'リアルタイム経営判断可能',
	AI_IMPROVEMENT_ACCURACY_FEATURE5: 'リスク予測・早期対応実現',

	// TechnologyStack コンポーネント
	TECH_STACK_TITLE: '技術スタック',
	TECH_STACK_DESC: '本ポートフォリオサイトは、最新のWeb技術とベストプラクティスを活用して構築されています。以下は主要な技術スタックの概要です。',
	TECH_FRONTEND_NAME: 'フロントエンド',
	TECH_STACK_FRONTEND_TITLE: 'フロントエンド',
	TECH_FRONTEND_ITEM1: 'Next.js 15.5.2',
	TECH_FRONTEND_ITEM2: 'React 19',
	TECH_FRONTEND_ITEM3: 'TypeScript',
	TECH_FRONTEND_ITEM4: 'Tailwind CSS',
	TECH_APP_NAME: 'アプリケーション',
	TECH_STACK_APP_TITLE: 'アプリケーション',
	TECH_APP_ITEM1: 'Node.js Runtime',
	TECH_APP_ITEM2: 'Next.js API Routes',
	TECH_APP_ITEM3: 'JWT Authentication',
	TECH_APP_ITEM4: 'bcrypt 暗号化',
	TECH_DB_NAME: 'データベース',
	TECH_STACK_DB_TITLE: 'データベース',
	TECH_DB_ITEM1: 'PostgreSQL',
	TECH_DB_ITEM2: 'SQLite',
	TECH_DB_ITEM3: 'Prisma ORM',
	TECH_DB_ITEM4: 'Redis Cache',
	TECH_INFRA_NAME: 'インフラ・デプロイ',
	TECH_STACK_INFRA_TITLE: 'インフラ・デプロイ',
	TECH_INFRA_ITEM1: 'Vercel',
	TECH_INFRA_ITEM2: 'Contabo VPS',
	TECH_INFRA_ITEM3: 'Docker',
	TECH_INFRA_ITEM4: 'Git/GitHub',

	// Features コンポーネント
	FEATURES_TITLE: '主な機能',
	FEATURES_OVERVIEW: '本ポートフォリオサイトの主な機能をご紹介します。これらの機能は、ユーザー体験の向上とセキュリティの強化を目的としています。',
	FEATURE_JWT_NAME: 'JWT認証',
	FEATURE_JWT_DESC: 'セキュアなJWTトークンベースの認証システム。HttpOnlyクッキーでXSS攻撃を防止。',
	FEATURE_ROLE_NAME: 'ロールベース制御',
	FEATURE_ROLE_DESC: 'User、Admin、Masterの3段階の権限レベルでアクセス制御を実現。',
	FEATURE_DB_NAME: 'データベース統合',
	FEATURE_DB_DESC: 'PostgreSQL + SQLiteによるデュアルデータベース構成で冗長性を確保。',
	FEATURE_POSTGRESQL_NAME: 'PostgreSQL統合',
	FEATURE_POSTGRESQL_DESC: '高性能なPostgreSQLデータベースでユーザー情報とセッションを安全に管理。',
	FEATURE_UI_NAME: 'レスポンシブUI',
	FEATURE_UI_DESC: 'Tailwind CSSによるモバイルフレンドリーな美しいユーザーインターフェース。',
	FEATURE_RESPONSIVE_NAME: 'レスポンシブUI',
	FEATURE_RESPONSIVE_DESC: 'Tailwind CSSによるモバイルフレンドリーな美しいユーザーインターフェース。',
	FEATURE_REALTIME_NAME: 'リアルタイム通信',
	FEATURE_REALTIME_DESC: 'WebSocketを使用したリアルタイムデータ更新とプッシュ通知。',
	FEATURE_PERFORMANCE_NAME: '高速パフォーマンス',
	FEATURE_PERFORMANCE_DESC: 'Next.js 15のTurbopackによる超高速ホットリロードとビルド最適化。',
	FEATURE_SECURITY_NAME: 'セキュリティ',
	FEATURE_SECURITY_DESC: 'bcryptによるパスワードハッシュ化、CSRF保護、セッション管理を実装。',

	// Contact コンポーネント
	CONTACT_TITLE: 'このポートフォリオについて',
	CONTACT_DESC: 'モダンなWebアプリケーション開発の技術スタックを実際に体験していただけるデモサイトです。フルスタック開発、認証システム、データベース統合の実装例をご覧いただけます。',
	CONTACT_BUTTON_TRY: '今すぐ試す',
	CONTACT_BUTTON_GITHUB: 'GitHub で見る',

	// 共通UI要素
	COMMON_LOADING: '読み込み中...',
	COMMON_ERROR: 'エラーが発生しました',
	COMMON_SUCCESS: '成功しました',
	COMMON_CANCEL: 'キャンセル',
	COMMON_SAVE: '保存',
	COMMON_EDIT: '編集',
	COMMON_DELETE: '削除',
	COMMON_CONFIRM: '確認',
	COMMON_CLOSE: '閉じる',
} as const;

export default labels;
